language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-22.0.1
  - android-22
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-android-support
  - extra-google-m2repository
notifications:
  email: false
script: "./gradlew assemble testDebug"
sudo: false
cache:
  directories:
  - "$HOME/.m2"
after_success:
- "./gradlew clean build uploadArchives"
env:
  global:
  - secure: CRG7/tJYa23bUD/uc0Ex/mVL7PEZYOJzO7lxYLSDpnJVEnv8rnG5IOmzYLmuUA4pIBQFSkUGqC1tCh6gqzOJogUNc46HzJziNHdBjuN8eQuF5DQ0hy9KLQCFXWAyW0qi9tyehSAkLxRYtWmfZTDo/P6LfESW7LRYgxo1N+pxTvM=
  - secure: hY1l1fAv5LXGP+1o/TJLEuLn6VFHbsg5pC3E5TyKu9HrnvjboqdMOdUMMRv4+t8Sl+gYLo2YEPNIDQgVVKoCvyow/Cupm6NGXIeROXxzg/WUK+95VyllMAXUaOwZXeH6ZPai/inXpX3jEYrha42xj9QiM4s/U1i+1wf4l+dlQH8=
